CHATO 53 : [FRONT] Edit user
tikoutare/chato pull request #80
Opened 2020-08-15 00:39 UTC by ara4dev

2020-08-20 16:12 UTC, tikoutare requested changes

2020-08-20 16:12 UTC, tikoutare commented on assets/pages/users/edit.jsx
> +
faut initialiser les champs ici avec la variable `user`

2020-08-20 16:12 UTC, tikoutare commented on assets/pages/users/edit.jsx
> +      setCounter(response.data);
```suggestion
      setUser(response.data);
```

2020-08-20 16:12 UTC, tikoutare commented on assets/pages/users/components/user-form.jsx
> +                                        type="text"
```suggestion
                                        type="email"
```

2020-08-20 16:12 UTC, tikoutare commented
formulaire crée par @aqchach-abdelaali  https://github.com/tikoutare/chato/pull/81

2020-08-20 18:50 UTC, tikoutare commented on assets/pages/users/edit.jsx
> +    ApiService.get(`/users/${id}`).then((response) => {
ce endpoint n'est pas encore dispo dans l'api c'est le jira CHATO-56, il faut le faire en premier

2020-08-20 21:10 UTC, ara4dev commented on assets/pages/users/edit.jsx
> +    ApiService.get(`/users/${id}`).then((response) => {
ok

2020-08-24 11:58 UTC, tikoutare approved these changes

2020-08-24 14:10 UTC, merged